name: Lint

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies & Lint code
      run: |
        python -m pip install --upgrade pip
        pip install -U .[setup]
        which pylint
        which python
        python -m pylint $(git ls-files '*.py') --output=pylint_output.txt
      shell: bash

    - name: Generate badge
      run: |
        pylint_note=$(grep -oP '(?<=rated at ).*(?=/10)' pylint_output.txt)
        anybadge --value=$pylint_note --file=pylint_note.svg pylint_note
      shell: bash

    - name: Archive badge
      uses: actions/upload-artifact@v3
      with:
        name: pylint_note
        path: pylint_note.svg
