name: Lint

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U .[setup]
      shell: bash

    - name: Lint code
      run: |
        mkdir -p ~/results/
        pylint demo --output-format=text > ~/results/pylint_output.txt
      shell: bash

    - name: Generate badge
      run: |
        pylint_note=$(grep -oP '(?<=rated at ).*(?=/10)' ~/results/pylint_output.txt)
        anybadge --value=$pylint_note --file=~/results/pylint_note.svg pylint_note
      shell: bash

    - name: Archive badge
      uses: actions/upload-artifact@v3
      with:
        name: pylint_note
        path: ~/results/pylint_note.svg
