name: Codecov

inputs:
  CODECOV_TOKEN:
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      
    - name: Install dependencies and run tests with coverage
      run: |
        python -m pip install --upgrade pip
        pip install -U .[setup]
        pytest --cov=demo
      shell: bash

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ inputs.CODECOV_TOKEN }}
      with:
        file: ./coverage.xml
