name: Main

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  codecov:
    uses: ./.github/workflows/codecov.yml

  build:
    uses: ./.github/workflows/build.yml

  metrics:
    uses: ./.github/workflows/metrics.yml
