name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U .[dev]

    - name: Run pytest
      run: |
        pytest --cov-report=xml --cov=package tests/

    - name: Run pylint
      run: |
        pylint package/

    - name: Upload coverage report
      uses: codecov/codecov-action@v2.1.0
      with:
        file: ./coverage.xml

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        username: jultou
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        context: .
        push: true
        tags: jultou/kaggle_mri_demo:latest

    - name: Add pylint badge
      uses: lowlighter/metrics@v4.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        user: username
        repo: repo
        metrics: pylint
        pylint_args: --fail-under=9.0
        pylint_glob: '**/*.py'

    - name: Add pytest-coverage badge
      uses: lowlighter/metrics@v4.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        user: jultou-raa
        repo: repo
        metrics: pytest-coverage
        pytest_coverage_args: --cov-report=xml --cov=package
        pytest_coverage_glob: '**/tests/*.py'